### ISSUE TITLE
Where should  libdxcompiler.so be placed?

### ISSUE THREAD

**Issue by Makogan** [Traverse-Research/hassle-rs#61]
The documentation mentions you should have the file on your environment, but merely placing it at the root of the project does not seem to allow the crate to find, it. It would be helpful for the error message to print the absolute path to where it is trying to find the .so/

**Comment by MarijnS95** [comment]
On Linux the `.so` is loaded from the working directory:

https://github.com/Traverse-Research/hassle-rs/blob/ddcdfc6032657b2b8d75d1bc55719d186ad7e55e/src/wrapper.rs#L468-L481

In general, that's the location `cargo run` is invoked from. But you can also pass a custom directory or whole path to `Dxc::new(Some(PathBuf::from("some/path/to/libdxcompiler.so")))`.

**Comment by Makogan** [comment]
I diged down the error stack and figured I was misreading the error message. The problem was I needed to install this:

`sudo apt install libtinfo5 `

I will piggy back off this thread however. I managed to get things running on debug mode, but on release I get a segfault:

```

Thread 1 "02_skinned_mesh" received signal SIGSEGV, Segmentation fault.
0x00007fffde9e8d69 in hlsl::DxcCreateBlobEncodingFromBlob(IDxcBlob*, unsigned int, unsigned int, bool, unsigned int, IMalloc*, IDxcBlobEncoding**) () from ./libdxcompiler.so

```

This is the invocation:

```rust
 let spirv = unsafe {
            compile_hlsl(
                &name.as_str(),
                &source.as_str(),
                "main",
                "cs_6_5",
                &vec!["-spirv"],
                &vec![],
            )
            .unwrap()
        };
        ```
        
        I have not modified the .so nor the library.

**Comment by MarijnS95** [comment]
> I diged down the error stack and figured I was misreading the error message. The problem was I needed to install this:

Oh right, yes, `libdxcompiler.so` provided by Microsoft still links against ancient ncurses5, which is gone on modern Linux distros and the latest Ubuntu.

> I will piggy back off this thread however. I managed to get things running on debug mode, but on release I get a segfault:

That is quite strange, the only reason I can think of is a mismatch between hassle-rs and DXC versions since there was an ABI break (for the better, to fix wrong vtable layout). See also the support table at https://github.com/Traverse-Research/hassle-rs#supported-dxc-versions-on-non-windows. However, then it also shouldn't have worked in debug mode.

**Comment by Makogan** [comment]
I originally got the so from embark, getting directly from the DXC gh page allows for proper error messages. i assume they compiled the library and stripped some stuff out of it. Sorry for bugging.

**Comment by Makogan** [comment]
Kajiya has the compiler.so file, but using it was causing segfaults on release.

**Comment by MarijnS95** [comment]
Yeah Kajiya is still on `0.5` even:

https://github.com/EmbarkStudios/kajiya/blob/5a124d58b8fc8795d37c933168c4ce98e986ce4c/crates/lib/kajiya-backend/Cargo.toml#LL21

**Comment by Makogan** [comment]
> 

I am getting confused about something. The DXC object is initialised inside `compile_hlsl` which does not take the path as a parameter. As a user I don;t know how to change the location of where the library will look for the so, it seems hard coded into the API by being encapsulated in the compile function.

**Comment by MarijnS95** [comment]
Yes we haven't updated the `compile_hlsl()` signature because it's already quite packed and only useful for one-off compilations, in most cases you want to load the `Dxc` library and construct the compiler and library only once and reuse it for many `.compile()` calls. That said, feel free to PR this addition to the function :)

At the same time the return value of `.compile()` (and friends) is terrible, and I have a few branches lying around that try to simplify and improve the return facility (i.e. always providing error context if available, regardless of function nor `result.get_status()` `HRESULT` etc), but nothing definitive yet. At least `compile_hlsl()` encapsulates this in some way, but I'd rather move that into `.compile()`.
