### ISSUE TITLE
[feature request] Serving the so with the library?

### ISSUE THREAD

**Issue by Makogan** [Traverse-Research/hassle-rs#62]
Is there any possibility of providing the so and dll binaries directly (similar to how kayija has the binary) instead of asking the user to collect it and install it in the right location?

Given that dxc is now open source I am not sure why the so needs to be manually collected by the user.

**Comment by MarijnS95** [comment]
`hassle-rs` is not a binary but a library crate so it depends completely on the projects _using `hassle-rs`_ to determine how they want to provide this lib to their users. That isn't a choice hassle-rs can make, since we cannot rely on any sort of stable path (there are ways, but that's out of scope).

Kajiya is one such user, as an engine that is mostly supposed to run out of the box when `cargo run` is _invoked from the root directory_, but it won't run when you give someone the executable from the target folder, and that's nothing we can cleanly address.

For example, the Vulkan SDK and modern Linux distros ship with (a package for) `libdxcompiler.so`/`dxcompiler.dll`, so there's no need to blow up crate sizes by including it (for multiple target architectures and OSes!) by default.

---

However, there is still hope for static linking. We discussed this shortly in #57 and while it is not very easy with `CMake` (it keeps track of many static libraries internally but doesn't combine them into a single archive, but that can be worked around) this opens the door to not having to deal with any library at all (after compiling your Rust crate!). The only "hassle" is during compilation then, where a static `libdxcompiler.a` needs to be acquired, shipped with `hassle-rs` (no, for the reasons mentioned above), or built on the spot like most `-sys` crates (though it is a rather heavy codebase). After your Rust binary is compiled it can be easily redistributed without having to worry about DXC anymore. And it works, will post progress in #57 shortly.

**Comment by MarijnS95** [comment]
Closing this as there's nothing actionable from our side. We provide the bindings to the library (stable API), not the library itself for the reasons given above.
